language: python
os: linux
dist: bionic
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-build.txt

pre_script: |
  python setup.py bdist_wheel
  pip install ./dist/traceflow*any.whl

# command to run tests
jobs:
  include:
    - stage: installing
      script: |
        python setup.py bdist_wheel
        pip install ./dist/traceflow*any.whl
    - stage: linting
      script: black --check .
    - stage: test
      script: |
        python setup.py bdist_wheel &&
        pip install ./dist/traceflow*any.whl &&
        sudo -E $(which traceflow) 1.1.1.1
    - stage: docker
      script: docker build -t traceflow .


script: pytest

notifications:
  email: false


