language: python 
os: linux
dist: bionic
python:
  - "3.7"
install:
  - pip install -r requirements.txt
# command to run tests
script: python setup.py bdist_wheel &&  pip install ./dist/traceflow*any.whl && sudo -E $(which traceflow) 1.1.1.1
