language: python
os: linux
dist: bionic
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-build.txt

script:
  - python setup.py bdist_wheel
  - pip install ./dist/traceflow*any.whl
  - black --check traceflow
  - black --check tests
  - pytest
  - sudo -E $(which traceflow) 1.1.1.1

notifications:
  email: false


